// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpazpfhhkgexshgdyjip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwYXpwZmhoa2dleHNoZ2R5amlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDYyMzUsImV4cCI6MjA3NDAyMjIzNX0.yWeJ5mlDohSz4hRVyQfVvSVcRD7jBjnktcvJ6MyWoo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});